language: node_js
node_js:
  - 6.6
before_install:
  # Repo for Yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - npm install -g npm@3.10.3
  - npm install -g gulp-cli
install:
  - npm install --no-optional
  - cd v3 && yarn && yarn run build:dll
after_success: npm run coverage
cache:
  directories:
  - $HOME/.yarn-cache
