#
# NOTE: You probably don't want to start this directly.
# Use infra/instance/start-prod.sh to start NUSMods in production.
#
version: '3.7'
services:
  website:
    build:
      context: .
      dockerfile: website/Dockerfile.prod
      args:
        - GIT_COMMIT_HASH
        - DATA_API_BASE_URL
    networks:
      - intranet
    expose:
      - 8080
      - 8081
    restart: on-failure
      - 'traefik.enable=true'
      - 'traefik.backend=website'
      - 'traefik.frontend.rule=HostRegexp:nusmods.com,{subdomain:[0-9]+}.nusmods.com'
      - 'traefik.port=8080'

  graphql:
    image: hasura/graphql-engine:v1.0.0-beta.2.cli-migrations
    volumes:
      - ./api/graphql/migrations:/hasura-migrations
    expose:
      - 8082
    depends_on:
      - 'postgres'
    env_file:
      - ./api/graphql/.env
    environment:
      - HASURA_GRAPHQL_SERVER_PORT=8082
      - HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:@postgres:5432/postgres
      - HASURA_GRAPHQL_UNAUTHORIZED_ROLE=public
    labels:
      - 'traefik.enable=true'
      - 'traefik.backend=graphql'
      - 'traefik.frontend.rule=HostRegexp:nusmods.com,{subdomain:[0-9]+}.nusmods.com;PathPrefixStrip:/api/graphql/'
      - 'traefik.port=8082'

  export:
    build:
      dockerfile: export/Dockerfile.prod
    env_file:
      - export/.env
    networks:
      - intranet
    expose:
      - 8083
    depends_on:
      - website
    init: true
    security_opt:
      - seccomp="infra/instance/chromium.seccomp.json"
    environment:
      - NODE_ENV=production
      - PORT=8083
      - HOST=0.0.0.0
    restart: on-failure
    labels:
      - 'traefik.enable=true'
      - 'traefik.backend=export'
      - 'traefik.frontend.rule=HostRegexp:nusmods.com,{subdomain:[0-9]+}.nusmods.com;PathPrefixStrip:/export/'
      - 'traefik.port=8083'

# Connect to a bridge network called 'intranet',
# which allows communication with other docker-compose setups
networks:
  intranet:
    external:
      name: machine_intranet

  postgres:
    image: postgres:11.4-alpine
    volumes:
      - db_data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.1
    environment:
      - discovery.type=single-node # Bypass bootstrap checks in single-node dev cluster. See: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-dev-mode
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
    volumes:
      - ./api/search/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - esdata01:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    expose:
      - 9200
    restart: on-failure

  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.1
    expose:
      - 5601
    environment:
      - SERVER_BASEPATH=/kibana
      - SERVER_REWRITEBASEPATH=true
    restart: on-failure

  es-importer:
    build:
      context: .
      dockerfile: api/search/Dockerfile.prod
    depends_on:
      - elasticsearch
    restart: on-failure

  proxy:
    image: abiosoft/caddy:php-no-stats
    ports:
      - ${EXPOSED_PORT}:2015
    env_file:
      - ./infra/instance/proxy.env
    volumes:
      - ./infra/instance/Caddyfile:/etc/Caddyfile
      - ./infra/instance/logs:/logs
      - ./infra/instance/.caddy:/root/.caddy
      - ./infra/instance/short_url.php:/srv/short_url.php
    restart: on-failure

volumes:
  db_data:
  esdata01:
