version: '3.6'
services:
  postgres:
    image: postgres:11.1-alpine
    volumes:
      - db_data:/var/lib/postgresql/data

  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-alpha40.cli-migrations
    volumes:
      - ./migrations:/hasura-migrations
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
    env_file:
      - ./.env
    environment:
      HASURA_GRAPHQL_DATABASE_URL: 'postgres://postgres:@postgres:5432/postgres'
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' # set to "false" to disable console
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: 'public'

  auth-server:
    build: .
    volumes:
      - ~/.cache/yarn:/home/node/.cache/yarn
      - .:/home/node/app
    ports:
      - '8081:8081'
    env_file:
      - ./.env
    environment:
      DATABASE_URL: 'postgres://postgres:@postgres:5432/postgres'
      HASURA_URL: 'http://graphql-engine:8080/v1alpha1/graphql'
      NODE_ENV: 'development'
      PORT: 8081
    user: ${CURRENT_UID:-1000:1000}

volumes:
  db_data:
