version: '3.6'
services:
  postgres:
    image: postgres:11.1-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-alpha38.cli-migrations
    volumes:
      - ./migrations:/hasura-migrations
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' # set to "false" to disable console
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: 'public'
      HASURA_GRAPHQL_ADMIN_SECRET: development
volumes:
  db_data:
