version: 2

defaults: &defaults
  docker:
    - image: circleci/node:8

restore_cache: &restore_node_deps
  name: Restore node_modules cache
  keys:
    - v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
    - v1-node-{{ arch }}-{{ .Branch }}-
    - v1-node-{{ arch }}-

save_cache: &save_node_deps
  name: Save node_modules cache
  key: v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
  paths:
    - node_modules

jobs:
  checkout:
    <<: *defaults
    working_directory: ~/nusmods
    steps:
      - checkout
      - run: echo $CIRCLE_COMPARE_URL | cut -d/ -f7
      - persist_to_workspace:
          root: .
          paths:
            - .

  data-server:
    <<: *defaults
    working_directory: ~/nusmods/api/data
    steps:
      - attach_workspace:
          at: ~/nusmods
      - restore_cache: *restore_node_deps
      - run: yarn
      - save_cache: *save_node_deps
      - run: yarn lint
      - run: yarn test --runInBand

  nus-scrapers:
    <<: *defaults
    working_directory: ~/nusmods/scrapers/nus
    steps:
      - attach_workspace:
          at: ~/nusmods
      - restore_cache: *restore_node_deps
      - run: yarn
      - save_cache: *save_node_deps
      - run: yarn lint
      - run: yarn test --runInBand
      - run:
          name: Build scraper
          environment:
            NODE_ENV: production
          command: yarn build:scraper

  nus-scrapers-v2:
    <<: *defaults
    working_directory: ~/nusmods/scrapers/nus-v2
    steps:
      - attach_workspace:
          at: ~/nusmods
      - restore_cache: *restore_node_deps
      - run: yarn
      - save_cache: *save_node_deps
      - run: yarn lint
      - run: yarn test --runInBand
      - run:
          name: Build scraper
          environment:
            NODE_ENV: production
          command: yarn build

  nusmoderator:
    <<: *defaults
    working_directory: ~/nusmods/packages/nusmoderator
    steps:
      - attach_workspace:
          at: ~/nusmods
      - restore_cache: *restore_node_deps
      - run: yarn
      - save_cache: *save_node_deps
      - run: yarn lint
      - run: yarn test --runInBand
      - run: yarn build
      - store_artifacts:
          path: dist
      - run: yarn docs
      - store_artifacts:
          path: README.md

  www:
    <<: *defaults
    working_directory: ~/nusmods/www
    environment:
      NODE_ENV: production
    steps:
      - attach_workspace:
          at: ~/nusmods
      - restore_cache: *restore_node_deps
      - run:
          name: Install dependencies
          environment:
            NODE_ENV: test
          command: yarn
      - save_cache: *save_node_deps
      - run:
          name: Type check code
          command: yarn flow
      - run:
          name: Lint code
          command: yarn lint:code --format junit -o reports/junit/js-lint-results.xml
      - run:
          name: Test code
          environment:
            NODE_ENV: test
            JEST_JUNIT_OUTPUT: reports/junit/js-test-results.xml
          command: |
            set -e
            yarn test --runInBand --reporters=default --reporters=jest-junit
            cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
      - run:
          name: Lint styles
          command: yarn lint:styles
      - run:
          name: Build web page
          command: yarn build
      - run:
          name: Report bundle size
          command: yarn size
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: dist

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout
      - data-server:
          requires:
            - checkout
      - nus-scrapers:
          requires:
            - checkout
      - nus-scrapers-v2:
          requires:
            - checkout
      - nusmoderator:
          requires:
            - checkout
      - www:
          requires:
            - checkout
