---
- command: bower install chdir={{ project_dir }}
- composer: working_dir={{ project_dir }}
- npm: path={{ project_dir }}
- npm: path={{ project_dir }}/api
- git:
    repo=https://github.com/YOURLS/YOURLS.git
    dest=/home/{{ user }}/modsn.us
    version=1.5.1
    accept_hostkey=yes
- git:
    repo=https://github.com/YOURLS/random-keywords.git
    dest=/home/{{ user }}/modsn.us/user/plugins/random-keywords
    accept_hostkey=yes
- template:
    src=yourls/user/config.php.j2
    dest=/home/{{ user }}/modsn.us/user/config.php
