debug = true
logLevel = "DEBUG"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
    [entryPoints.http.redirect]
    entryPoint = "https"

  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
    [entryPoints.https.redirect]
      permanent=true
      regex = "^https://www.(.*)"
      replacement = "https://$1"

  [entryPoints.traefik]
  address = ":5678"

# [retry]
# attempts = 3
# maxMem = 3

[api]
entryPoint = "traefik"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "localhost"
watch = true
exposedByDefault = false

[acme]
entryPoint = "https"
email = "mods@nusmods.com"
storage = "/acme.json"
onHostRule = true
[acme.dnsChallenge]
  provider = "cloudflare"
[[acme.domains]]
  main = "*.nusmods.com"
  sans = ["nusmods.com"]

[backends]
  [backends.fake]
    [backends.fake.servers.s1]
      url="http://1.2.3.4"

[frontends]
[frontends.r1]
  backend = "fake"
  [frontends.r1.redirect]
    regex = "^https://.+/api/(.*)"
    replacement = "https://api.nusmods.com/$1"
    permanent = false
[frontends.r2]
  backend = "fake"
  [frontends.r2.redirect]
    regex = "^https://nextbus.nusmods.com/arrival(.*)"
    replacement = "https://nextbus.comfortdelgro.com.sg/eventservice.svc/shuttleservice$1"
    permanent = false
[frontends.r3]
  backend = "fake"
  [frontends.r3.redirect]
    regex = "^https://github.nusmods.com/repo(.*)"
    replacement = "https://api.github.com/repos/nusmodifications/nusmods$1"
    permanent = false
[frontends.r4]
  backend = "fake"
  [frontends.r4.redirect]
    regex = "^https://github.nusmods.com/venues(.*)"
    replacement = "https://raw.githubusercontent.com/nusmodifications/nusmods/master/website/src/data/venues.json"
    permanent = false
